# Generated by Django 5.2.5 on 2026-05-13 19:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('lifetime', 'Lifetime')], max_length=30)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('expiration_date', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
