# Generated by Django 5.2.5 on 2025-08-23 08:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_alter_membership_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='plan_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('lifetime', 'Lifetime')], max_length=30),
        ),
        migrations.AlterField(
            model_name='membership',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
