# Generated by Django 5.2.5 on 2026-04-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_alter_membership_plan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
