"""
Django settings for gym_management project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y*au1dzkd3jmx+bb_4r8j%3*fzar$x@(5funeo*fy2ndzs=!b-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_filters',
    'drf_spectacular',

    # For auth and DRF 
     'rest_framework',
     'rest_framework.authtoken',
     'dj_rest_auth',
     'rest_framework_simplejwt.token_blacklist',

     #gym_management apps
      # Your apps
    'users',
    'memberships',
    'payments',
    'documents',
    'activity_logs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gym_management.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gym_management.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Uses DATABASE_URL in production (Docker / AWS RDS); falls back to SQLite for local dev.

import dj_database_url

DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        conn_health_checks=True,
    )
}

# ---------------------------------------------------------------------------
# Redis / Cache configuration
# ---------------------------------------------------------------------------

REDIS_URL = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/0")

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Graceful fallback: ignore connection errors in dev
            "IGNORE_EXCEPTIONS": DEBUG,
        },
    }
}

# Fallback to in-memory cache if Redis is unavailable during development
if DEBUG:
    try:
        import redis as _redis_lib
        _r = _redis_lib.from_url(REDIS_URL, socket_connect_timeout=1)
        _r.ping()
    except Exception:
        CACHES = {
            "default": {
                "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
                "LOCATION": "gym-token-blacklist",
            }
        }

# Redis key prefix for blacklisted refresh tokens
REDIS_TOKEN_BLACKLIST_PREFIX = "bl:refresh:"

# ---------------------------------------------------------------------------
# Celery configuration (uses same Redis instance)
# ---------------------------------------------------------------------------

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"


# ---------------------------------------------------------------------------
# Password hashers — Argon2 is preferred (OWASP recommendation)
# ---------------------------------------------------------------------------

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# ---------------------------------------------------------------------------
# JWT / Cookie configuration
# ---------------------------------------------------------------------------

# Cookie names used by users.authentication.CookieJWTAuthentication
JWT_AUTH_COOKIE = "gym_access_token"
JWT_AUTH_REFRESH_COOKIE = "gym_refresh_token"

# In production set this to True (requires HTTPS)
JWT_COOKIE_SECURE = not DEBUG

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
}

# ---------------------------------------------------------------------------
# Django REST Framework
# ---------------------------------------------------------------------------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.CookieJWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_THROTTLE_CLASSES': [],
    'DEFAULT_THROTTLE_RATES': {
        'login': '5/min',
        'password_reset': '3/min',
        'token_refresh': '10/min',
        'mfa_verify': '5/min',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Gym Management System API',
    'DESCRIPTION': 'REST API for managing gym memberships, payments, documents, users, and activity logs.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
}

#the user model
AUTH_USER_MODEL = "users.User"

# CSRF configuration for SPA + cookie-based JWT auth
CSRF_COOKIE_HTTPONLY = False          # JS must read the CSRF cookie to send the X-CSRFToken header
CSRF_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SECURE = not DEBUG        # Require HTTPS in production
CSRF_TRUSTED_ORIGINS = [
    os.environ.get("FRONTEND_URL", "http://localhost:3000"),
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
]


# ---------------------------------------------------------------------------
# Email configuration (console backend for dev; swap for SMTP in production)
# ---------------------------------------------------------------------------

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@gym.local")
FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:3000")

# Signed-token lifetimes (seconds)
EMAIL_VERIFY_TOKEN_MAX_AGE = 60 * 60 * 24      # 24 hours
PASSWORD_RESET_TOKEN_MAX_AGE = 60 * 30          # 30 minutes

# Signing salts (change per environment via env vars if desired)
EMAIL_VERIFY_SALT = "email-verify"
PASSWORD_RESET_SALT = "password-reset"


# ---------------------------------------------------------------------------
# OAuth 2.0 / OpenID Connect providers
# ---------------------------------------------------------------------------

OAUTH_PROVIDERS = {
    "google": {
        "client_id": os.environ.get("GOOGLE_CLIENT_ID", ""),
        "client_secret": os.environ.get("GOOGLE_CLIENT_SECRET", ""),
        "token_url": "https://oauth2.googleapis.com/token",
        "userinfo_url": "https://www.googleapis.com/oauth2/v3/userinfo",
        "redirect_uri": os.environ.get(
            "GOOGLE_REDIRECT_URI",
            f"{os.environ.get('FRONTEND_URL', 'http://localhost:3000')}/auth/callback/google",
        ),
    },
    "github": {
        "client_id": os.environ.get("GITHUB_CLIENT_ID", ""),
        "client_secret": os.environ.get("GITHUB_CLIENT_SECRET", ""),
        "token_url": "https://github.com/login/oauth/access_token",
        "userinfo_url": "https://api.github.com/user",
        "emails_url": "https://api.github.com/user/emails",
        "redirect_uri": os.environ.get(
            "GITHUB_REDIRECT_URI",
            f"{os.environ.get('FRONTEND_URL', 'http://localhost:3000')}/auth/callback/github",
        ),
    },
}


# ---------------------------------------------------------------------------
# MFA (Multi-Factor Authentication) — TOTP
# ---------------------------------------------------------------------------

# Fernet symmetric key for encrypting TOTP secrets at rest.
# Generate one with: python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())"
MFA_ENCRYPTION_KEY = os.environ.get(
    "MFA_ENCRYPTION_KEY",
    "ChZrx-wKujPV283ihCsYnYwRUWlvxSBFKX_qFobGUz4=",  # dev only — override in production
)

MFA_ISSUER_NAME = "Gym Management"
MFA_TOKEN_SALT = "mfa-challenge"
MFA_TOKEN_MAX_AGE = 60 * 5          # 5 minutes to complete MFA challenge
MFA_BACKUP_CODE_COUNT = 10


# ---------------------------------------------------------------------------
# Structured Logging
# ---------------------------------------------------------------------------

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "sensitive_data": {
            "()": "gym_management.logging_filters.SensitiveDataFilter",
        },
    },
    "formatters": {
        "json": {
            "()": "gym_management.logging_filters.JSONFormatter",
        },
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "json" if not DEBUG else "verbose",
            "filters": ["sensitive_data"],
        },
        "file": {
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "app.log",
            "maxBytes": 10 * 1024 * 1024,  # 10 MB
            "backupCount": 5,
            "formatter": "json",
            "filters": ["sensitive_data"],
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "file"],
            "level": "WARNING",
            "propagate": False,
        },
        "users": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console", "file"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Ensure the logs directory exists
(BASE_DIR / "logs").mkdir(exist_ok=True)


CHAPA_PUBLIC_KEY = os.environ.get('CHAPA_PUBLIC_KEY', 'CHAPUBK_TEST-tVCPOaCbJz1qHETIJinaXc3x9IJoAst4')
CHAPA_SECRET_KEY = os.environ.get('CHAPA_SECRET_KEY', 'CHASECK_TEST-ZpoCBqm7ZCvQ3m5lhFuXz2zvkhhPNKnb')